name: Deploy to gh-pages (fallback)

on:
  push:
    branches: [ main ]

jobs:
  deploy-ghpages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create runtime env file (env.js)
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          mkdir -p frontend/examples
          cat > frontend/examples/env.js << 'EOF'
          window.__ENV__ = {
            OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY}"
          };
          EOF

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
          publish_branch: gh-pages
