name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create runtime env file (env.js)
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          mkdir -p frontend/examples
          cat > frontend/examples/env.js << 'EOF'
          window.__ENV__ = {
            OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY}"
          };
          EOF

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
